unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'wfxr/tmux-power'
# set -g @tmux_power_theme "everforest"

# Start window numbering at 1
set -g base-index 1


# Tell tmux to support Kitty's cursor shapes
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-kitty:Cc=\E[%p1%d q:Se=\E[2 q'

# Start pane numbering at 1
set -w -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

set -g status-position top

# Load the current Hellwal theme for tmux-power
if-shell '[ -f ~/.cache/hellwal/tmux.conf ]' \
    'source-file ~/.cache/hellwal/tmux.conf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

